version: "3.1"
services:
  www:
    build: .
    ports:
      # - "8001:80"
      - "80:80"
    volumes:
      - ./www:/var/www/html/
    # links:
    #   - db
    depends_on:
      - db
    networks:
      - lamp_network

  db:
    image: mariadb:10.8.2-rc-focal
    container_name: appsDB
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - lamp_network
    environment:
      # MYSQL_DATABASE: myDb
      MARIADB_ROOT_PASSWORD: 12345678

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    networks:
      - lamp_network
    environment:
      PMA_HOST: db

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

networks:
  lamp_network:

volumes:
  persistent:
  portainer_data:
